### ISSUE TITLE
Ermine 1.0-2.0 roadmap

### ISSUE THREAD

**Issue by hbiblia** [hbiblia/ermine-engine#3]
Aquí esta mi lista de deseos para la primera versión de Ermine. Sientase libre de comentar aquí acerca de las mejoras propuestas o, si tiene algún requisito / característica especifica.

- [ ] **Renderizado**: soporte según el sistema (**DirectX**, **GL**, **Metal**).
- [ ] **Renderizado**: Unificar el 2D y 3D estilo Unity.
- [ ] **Renderizado**: Optimizar el renderizado 3D.
- [ ] **Editor**: Cambios en la UI del editor.
- [ ] **Editor**: Mejorar la velocidad de carga.
- [ ] **Editor**: Probar el proyecto en el viewport.
- [ ] **File**: Crear nuevos tipos de archivos  ( **.scene**, **.actor**, **.anim**, **.particle** y otros )
- [ ] **Core**: Reorganizar proyecto.
- [ ] **Core-Resource**: Eliminar el recurso res:\\\ al utilizarlo directamente.
- [ ] **Core-UI**: Agregar nuevos Widget a la UI
- [ ] **Core**: **ECS** No mas nodos bienvenido al mundo de Entity System Components.
- [ ] **API**: Mejorar
- [ ] **Script**: Deprecar GDScript y bienvenido [Votación](JS, Python, C#) y C++.
- [ ] **Script**: Visual Script será tan importante como en UE4.

Sólo tenga en cuenta que voy a seguir actualizando esta lista según sea necesario!
